spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/android?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: owPGeirRh0(l
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB
        enabled: true
server:
  port: 8080
